#!/usr/bin/env bash

if [ "$LLVM_BUILD_DIR" == "" ]; then
	llvm_link="`which llvm-link`"
else
	llvm_link="$LLVM_BUILD_DIR/bin/llvm-link"
fi

if [ "$llvm_link" == "" ]; then
	echo "No 'llvm-link' in \$PATH and LLVM_BUILD_DIR not set"
	exit 1
fi

OUT=$1

shift # skip output filename

if [[ -n "$@" ]] # check that we have some files to link
then
  $llvm_link -libmd -o $OUT $@
fi
